<a href="https://colab.research.google.com/github/07ahashan/ATM_Interface/blob/main/ML_Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#import libraries
import numpy as np
import pandas as pd

In [5]:
# Uploading the files
mydata1=pd.read_excel("/content/drive/MyDrive/Preprocessing_Data_I (1).xlsx")
mydata2=pd.read_excel("/content/drive/MyDrive/Preprocessing_Data_II.csv (1).xlsx")

In [6]:
#Merge the files

myNewdata=mydata1.append(mydata2)
myNewdata

<ipython-input-6-1e1f321c75c2>:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  myNewdata=mydata1.append(mydata2)

,SL No,Reviewer_Skill,Review_Type,Domain_Knowledge,Review_Time,Test_Coverage,Review_Coverage,Reuse,Review_Rate,Sprint_Prod
0,1,4,Fresher,4,30.0,100.0,70.0,30.0,3,0.46
1,2,5,Experienced,5,20.0,70.0,100.0,15.0,1,0.08
2,3,4,Fresher,4,20.0,70.0,100.0,15.0,2,0.11
3,4,4,Fresher,4,30.0,70.0,70.0,50.0,4,0.73
4,5,5,Experienced,5,NaN,100.0,NaN,50.0,4,0.50
5,6,3,Fresher,3,30.0,100.0,70.0,25.0,1,0.35
6,7,4,Experienced,4,30.0,70.0,100.0,25.0,2,0.19
7,8,4,Fresher,4,20.0,70.0,70.0,10.0,4,0.23
8,9,3,Fresher,3,30.0,70.0,70.0,20.0,3,0.16
9,10,5,Experienced,5,20.0,70.0,100.0,70.0,4,1.60
10,11,3,Fresher,3,30.0,100.0,70.0,30.0,1,0.37
11,12,4,Fresher,4,30.0,100.0,70.0,50.0,2,0.76
12,13,4,Fresher,4,30.0,100.0,100.0,50.0,2,0.66
13,14,5,Experienced,5,20.0,70.0,100.0,70.0,4,1.27
14,15,4,Experienced,4,30.0,50.0,50.0,50.0,2,0.57
15,16,4,Fresher,4,30.0,NaN,50.0,50.0,3,0.52
16,17,4,Experienced,4,30.0,50.0,50.0,50.0,2,0.50
17,18,5,Experienced,5,20.0,70.0,70.0,70.0,4,0.99
18,19,5,Experienced,5,20.0,70.0,70.0,70.0,4,0.92
19,20,3,Fresher,3,20.0,70.0,70.0,15.0,3,0.26
0,21,5,Experienced,5,20.0,50.0,50.0,50.0,3,0.54
1,22,3,Fresher,3,20.0,100.0,70.0,10.0,2,0.18
2,23,4,Fresher,4,20.0,100.0,NaN,10.0,3,0.37
3,24,4,Fresher,4,20.0,100.0,70.0,20.0,3,0.47
4,25,3,Fresher,3,NaN,100.0,70.0,25.0,1,0.37
5,26,4,Experienced,4,30.0,70.0,50.0,70.0,2,0.78
6,27,3,Fresher,3,20.0,100.0,70.0,20.0,1,0.34
7,28,3,Fresher,3,20.0,100.0,70.0,20.0,1,0.38
8,29,4,Experienced,4,30.0,100.0,70.0,NaN,2,0.52
9,30,5,Experienced,5,20.0,100.0,70.0,70.0,4,1.26
10,31,4,Experienced,4,30.0,100.0,70.0,10.0,1,0.32
11,32,4,Experienced,4,30.0,70.0,100.0,10.0,1,0.09
12,33,5,Experienced,5,20.0,70.0,70.0,70.0,4,1.69
13,34,5,Experienced,5,30.0,50.0,50.0,50.0,2,0.73

In [7]:
# checking the details from the merge files
myNewdata.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34 entries, 0 to 13
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SL No             34 non-null     int64
 1   Reviewer_Skill    34 non-null     int64
 2   Review_Type       34 non-null     object
 3   Domain_Knowledge  34 non-null     int64
 4   Review_Time       32 non-null     float64
 5   Test_Coverage     33 non-null     float64
 6   Review_Coverage   32 non-null     float64
 7   Reuse             33 non-null     float64
 8   Review_Rate       34 non-null     int64
 9   Sprint_Prod       34 non-null     float64
dtypes: float64(5), int64(4), object(1)
memory usage: 2.9+ KB

In [8]:
#Describe the file is totally different from the file info()
# Its find all the missing values

myNewdata.describe()

,SL No,Reviewer_Skill,Domain_Knowledge,Review_Time,Test_Coverage,Review_Coverage,Reuse,Review_Rate,Sprint_Prod
count,34.000000,34.000000,34.000000,32.000000,33.000000,32.000000,33.000000,34.000000,34.000000
mean,17.500000,4.058824,4.058824,25.000000,81.212121,72.812500,37.878788,2.500000,0.566765
std,9.958246,0.736131,0.736131,5.080005,18.499590,16.506963,22.291755,1.134847,0.405849
min,1.000000,3.000000,3.000000,20.000000,50.000000,50.000000,10.000000,1.000000,0.080000
25%,9.250000,4.000000,4.000000,20.000000,70.000000,70.000000,20.000000,2.000000,0.325000
50%,17.500000,4.000000,4.000000,25.000000,70.000000,70.000000,30.000000,2.000000,0.485000
75%,25.750000,5.000000,5.000000,30.000000,100.000000,70.000000,50.000000,3.750000,0.730000
max,34.000000,5.000000,5.000000,30.000000,100.000000,100.000000,70.000000,4.000000,1.690000

In [9]:

# Checking the null values
myNewdata.isna()

,SL No,Reviewer_Skill,Review_Type,Domain_Knowledge,Review_Time,Test_Coverage,Review_Coverage,Reuse,Review_Rate,Sprint_Prod
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,True,False,True,False,False,False
5,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,True,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,True,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,True,False,False
9,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False

In [10]:
# Checking the null values
myNewdata.isna().sum().sort_values()

SL No               0
Reviewer_Skill      0
Review_Type         0
Domain_Knowledge    0
Review_Rate         0
Sprint_Prod         0
Test_Coverage       1
Reuse               1
Review_Time         2
Review_Coverage     2
dtype: int64

In [11]:
# Checking the null values and arranging them in the Ascending order
myNewdata.isna().sum().sort_values(ascending = True)

SL No               0
Reviewer_Skill      0
Review_Type         0
Domain_Knowledge    0
Review_Rate         0
Sprint_Prod         0
Test_Coverage       1
Reuse               1
Review_Time         2
Review_Coverage     2
dtype: int64

Lets understand the concept about the varous type of data in the dataset.

1. Numerical Data
    a)Time based data
    b)Continue Data

2. Categrogical data
    a)Ordinal data
    b)Nominal Data

In [12]:
#convert the categrogical data into numerical

from sklearn.preprocessing import LabelEncoder as lb
myNewdata["Review_Type"]=lb().fit_transform(myNewdata["Review_Type"])
myNewdata.info()

# converted successfully

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34 entries, 0 to 13
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SL No             34 non-null     int64
 1   Reviewer_Skill    34 non-null     int64
 2   Review_Type       34 non-null     int64
 3   Domain_Knowledge  34 non-null     int64
 4   Review_Time       32 non-null     float64
 5   Test_Coverage     33 non-null     float64
 6   Review_Coverage   32 non-null     float64
 7   Reuse             33 non-null     float64
 8   Review_Rate       34 non-null     int64
 9   Sprint_Prod       34 non-null     float64
dtypes: float64(5), int64(5)
memory usage: 2.9 KB

In [14]:
#checking whether the data is converted successfully
#check out the Review type the data has been changed from the numric value to categolical value....
myNewdata.head()

,SL No,Reviewer_Skill,Review_Type,Domain_Knowledge,Review_Time,Test_Coverage,Review_Coverage,Reuse,Review_Rate,Sprint_Prod
0,1,4,1,4,30.0,100.0,70.0,30.0,3,0.46
1,2,5,0,5,20.0,70.0,100.0,15.0,1,0.08
2,3,4,1,4,20.0,70.0,100.0,15.0,2,0.11
3,4,4,1,4,30.0,70.0,70.0,50.0,4,0.73
4,5,5,0,5,NaN,100.0,NaN,50.0,4,0.50

In [15]:
#Option 1: Discard all records with missing values
myData=myNewdata.dropna()
myData.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 29 entries, 0 to 13
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SL No             29 non-null     int64
 1   Reviewer_Skill    29 non-null     int64
 2   Review_Type       29 non-null     int64
 3   Domain_Knowledge  29 non-null     int64
 4   Review_Time       29 non-null     float64
 5   Test_Coverage     29 non-null     float64
 6   Review_Coverage   29 non-null     float64
 7   Reuse             29 non-null     float64
 8   Review_Rate       29 non-null     int64
 9   Sprint_Prod       29 non-null     float64
dtypes: float64(5), int64(5)
memory usage: 2.5 KB

In [16]:
#Option 2: Repalce missing values with centeral tendencies
myData=myNewdata
#Two missing values of Review_Time with mean
myData.Review_Time.fillna(myData.Review_Time.mean(), inplace= True)
myNewdata.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34 entries, 0 to 13
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SL No             34 non-null     int64
 1   Reviewer_Skill    34 non-null     int64
 2   Review_Type       34 non-null     int64
 3   Domain_Knowledge  34 non-null     int64
 4   Review_Time       34 non-null     float64
 5   Test_Coverage     33 non-null     float64
 6   Review_Coverage   32 non-null     float64
 7   Reuse             33 non-null     float64
 8   Review_Rate       34 non-null     int64
 9   Sprint_Prod       34 non-null     float64
dtypes: float64(5), int64(5)
memory usage: 2.9 KB